<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference
            Include="Mapster.DependencyInjection"
            Version="1.0.1"
        />
        <PackageReference
            Include="Microsoft.AspNetCore.Authentication.JwtBearer"
            Version="10.0.1"
        />
        <PackageReference
            Include="Microsoft.IdentityModel.JsonWebTokens"
            Version="8.15.0"
        />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Data\" />
        <Folder Include="Data\DatabaseContext\" />
        <Folder Include="Services\" />
        <Folder Include="Topics\Commands\" />
        <Folder Include="Topics\Commands\CreateTopic\" />
        <Folder Include="Topics\Mapping\" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
</Project>
