global using Application.Data.DatabaseContext;
global using Application.Dtos;
global using Application.Exceptions;
global using Application.Extensions;
global using Application.Services;
global using Domain.Entities;
global using Domain.ValueObjects;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
